name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  cache-modules:
    uses: Badi-Cal/badi-events-app/.github/workflows/cache.yml@c8b3734fc3a7c63f988617ff65893243bbcc18c9
    with:
      cache-name: 'cache-node-modules'

  build-test-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    needs: cache-modules

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      if: needs.cache-modules.cache-hit != 'true'
      run: npm install

    - name: Run e2e tests
      run: npm run test:e2e:ci
      env:
        CI: true

    - name: Build SPA
      run: npm run build

  deploy-ansible:
    needs: build-test-deploy
    runs-on: ubuntu-latest
    env:
      DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
      HOSTS: ${{ secrets.HOSTS }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}

    steps:
    - uses: actions/checkout@v2

    - name: Install Ansible
      run: source ./scripts/setup.sh

    - name: Run deploy playbook
      run: ansible-playbook ./config/playbooks/deploy.yml --extra-vars ansible_ssh_user=${DEPLOY_USER}
