name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build-test-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    - run: npm run test:e2e:ci
      env:
        CI: true
  deployAnsible:
    needs: build-test-deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Ansible
      env:
        DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        HOSTS: ${{ secrets.HOSTS }}
      run: |
        sudo apt update -y
        sudo apt install software-properties-common -y
        sudo apt-add-repository --yes --update ppa:ansible/ansible
        sudo apt install ansible -y
        cd config
        echo "$DEPLOY_SSH_KEY" > id_rsa
        chmod go-rwx id_rsa
        eval "$(ssh-agent -s)"
        ssh-add id_rsa
        mkdir ~/.ssh
        python set_up_keys.py
        python make_hosts.py
        ansible-playbook playbooks/deploy.yml --extra-vars ansible_ssh_user=${{ secrets.DEPLOY_USER }}
