name: Node.js test

on:
  push:
    branches-ignore: [ master ]
  pull_request:
    branches-ignore: [ master ]

jobs:
  cache-modules:
    uses: Badi-Cal/badi-events-app/.github/workflows/cache.yml@ce32e880e7b9e05b3a985b4af7192bb9272ecd10
    with:
      cache-name: 'cache-node-modules'

  build-test:
    runs-on: ubuntu-latest

    container:
      image: cypress/included:3.8.3

    strategy:
      matrix:
        node-version: [14]

    needs: cache-modules

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      if: needs.cache-modules.outputs.cache-hit != 'true'
      run: npm install

    - name: Run e2e tests
      run: npm run test:e2e:ci
