name: Node.js test

on:
  push:
    branches-ignore: [ master ]
  pull_request:
    branches-ignore: [ master ]

jobs:
  build-test:

    runs-on: ubuntu-latest
    container:
      image: cypress/included:3.8.3

    strategy:
      matrix:
        node-version: [14]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: Run e2e tests
      run: npm run test:e2e:ci
